name: appAgent
options:
  #minimumXcodeGenVersion: "2.39.1"
  minimumXcodeGenVersion: "2.42.0"
  bundleIdPrefix: at.co.weinmann
  deploymentTarget:
    #iOS: "10.0"
    iOS: "16.0"
targets:
  appAgent:
    type: application
    platform: iOS
    sources:
      - path: appAgent
        excludes:
          - Excludes
    settings:
      #SWIFT_VERSION: "4.0"
      #SWIFT_VERSION: "5.10.1"
      #SWIFT_VERSION: "6.0.1"
      CODE_SIGN_ENTITLEMENTS: appAgent/App.entitlements
    scheme:
      configVariants:
