name: appAgent
options:
  #minimumXcodeGenVersion: "2.39.1"
  minimumXcodeGenVersion: "2.42.0"
  bundleIdPrefix: at.co.weinmann
  deploymentTarget:
    #iOS: "10.0"
    iOS: "17.0"
targets:
  appAgent:
    type: application
    platform: iOS
    sources:
      - path: appAgent
        excludes:
          - Excludes
          #- $(APP_ICONSET_EXCLUDE)
    settings:
      #SWIFT_VERSION: "4.0"
      #SWIFT_VERSION: "5.10.1"
      #SWIFT_VERSION: "6.0.1"
      CODE_SIGN_ENTITLEMENTS: appAgent/App.entitlements
      
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: $(BITRISE_BUILD_NUMBER)
      
      #ASSETCATALOG_COMPILER_APPICON_NAME: $(APP_ICONSET)
      
      DEAD_CODE_STRIPPING: YES
      SWIFT_OPTIMIZATION_LEVEL: "-Osize"
      OTHER_LDFLAGS: "-Wl,-dead_strip -Xlinker -S"
      
      USR_APPICON_PRIMARY: $(ENV_APPICON_PRIMARY)
      USR_APPICON_ALT1: $(ENV_APPICON_ALT1)
      ASSETCATALOG_COMPILER_APPICON_NAME: $(USR_APPICON_PRIMARY)
      #ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES: $(USR_APPICON_ALT1)
      ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES: "DevIconAlt1"
      
    scheme:
      configVariants:
